In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nifty50-stock-market-data/HDFCBANK.csv
/kaggle/input/nifty50-stock-market-data/GRASIM.csv
/kaggle/input/nifty50-stock-market-data/WIPRO.csv
/kaggle/input/nifty50-stock-market-data/stock_metadata.csv
/kaggle/input/nifty50-stock-market-data/BPCL.csv
/kaggle/input/nifty50-stock-market-data/INFY.csv
/kaggle/input/nifty50-stock-market-data/LT.csv
/kaggle/input/nifty50-stock-market-data/RELIANCE.csv
/kaggle/input/nifty50-stock-market-data/BRITANNIA.csv
/kaggle/input/nifty50-stock-market-data/INFRATEL.csv
/kaggle/input/nifty50-stock-market-data/HEROMOTOCO.csv
/kaggle/input/nifty50-stock-market-data/HINDUNILVR.csv
/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv
/kaggle/input/nifty50-stock-market-data/MM.csv
/kaggle/input/nifty50-stock-market-data/HDFC.csv
/kaggle/input/nifty50-stock-market-data/JSWSTEEL.csv
/kaggle/input/nifty50-stock-market-data/TITAN.csv
/kaggle/input/nifty50-stock-market-data/HINDALCO.csv
/kaggle/input/nifty50-stock-market-data/AXISBANK.csv
/kaggle/input/nifty50-stock-market-data/HCLTECH.csv
/kaggle/input/nifty50-stock-market-data/ADANIPORTS.csv
/kaggle/input/nifty50-stock-market-data/GAIL.csv
/kaggle/input/nifty50-stock-market-data/NIFTY50_all.csv
/kaggle/input/nifty50-stock-market-data/BAJAJFINSV.csv
/kaggle/input/nifty50-stock-market-data/BAJFINANCE.csv
/kaggle/input/nifty50-stock-market-data/ICICIBANK.csv
/kaggle/input/nifty50-stock-market-data/ZEEL.csv
/kaggle/input/nifty50-stock-market-data/ASIANPAINT.csv
/kaggle/input/nifty50-stock-market-data/IOC.csv
/kaggle/input/nifty50-stock-market-data/TATASTEEL.csv
/kaggle/input/nifty50-stock-market-data/COALINDIA.csv
/kaggle/input/nifty50-stock-market-data/NESTLEIND.csv
/kaggle/input/nifty50-stock-market-data/DRREDDY.csv
/kaggle/input/nifty50-stock-market-data/ONGC.csv
/kaggle/input/nifty50-stock-market-data/EICHERMOT.csv
/kaggle/input/nifty50-stock-market-data/UPL.csv
/kaggle/input/nifty50-stock-market-data/SUNPHARMA.csv
/kaggle/input/nifty50-stock-market-data/ULTRACEMCO.csv
/kaggle/input/nifty50-stock-market-data/CIPLA.csv
/kaggle/input/nifty50-stock-market-data/SHREECEM.csv
/kaggle/input/nifty50-stock-market-data/VEDL.csv
/kaggle/input/nifty50-stock-market-data/TCS.csv
/kaggle/input/nifty50-stock-market-data/NTPC.csv
/kaggle/input/nifty50-stock-market-data/MARUTI.csv
/kaggle/input/nifty50-stock-market-data/KOTAKBANK.csv
/kaggle/input/nifty50-stock-market-data/ITC.csv
/kaggle/input/nifty50-stock-market-data/BAJAJ-AUTO.csv
/kaggle/input/nifty50-stock-market-data/SBIN.csv
/kaggle/input/nifty50-stock-market-data/INDUSINDBK.csv
/kaggle/input/nifty50-stock-market-data/BHARTIARTL.csv
/kaggle/input/nifty50-stock-market-data/TECHM.csv
/kaggle/input/nifty50-stock-market-data/POWERGRID.csv

In [2]:
df=pd.read_csv('/kaggle/input/nifty50-stock-market-data/TATAMOTORS.csv')
print(df.isna())
filtered=df.dropna()
filtered

       Date  Symbol  Series  Prev Close   Open   High    Low   Last  Close  \
0     False   False   False       False  False  False  False  False  False
1     False   False   False       False  False  False  False  False  False
2     False   False   False       False  False  False  False  False  False
3     False   False   False       False  False  False  False  False  False
4     False   False   False       False  False  False  False  False  False
...     ...     ...     ...         ...    ...    ...    ...    ...    ...
5301  False   False   False       False  False  False  False  False  False
5302  False   False   False       False  False  False  False  False  False
5303  False   False   False       False  False  False  False  False  False
5304  False   False   False       False  False  False  False  False  False
5305  False   False   False       False  False  False  False  False  False

       VWAP  Volume  Turnover  Trades  Deliverable Volume  %Deliverble
0     False   False     False    True                True         True
1     False   False     False    True                True         True
2     False   False     False    True                True         True
3     False   False     False    True                True         True
4     False   False     False    True                True         True
...     ...     ...       ...     ...                 ...          ...
5301  False   False     False   False               False        False
5302  False   False     False   False               False        False
5303  False   False     False   False               False        False
5304  False   False     False   False               False        False
5305  False   False     False   False               False        False

[5306 rows x 15 columns]

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
2850,2011-06-01,TATAMOTORS,EQ,1095.3,1096.0,1097.0,1075.60,1077.25,1079.90,1083.36,2412309,2.613407e+14,76698.0,1152083.0,0.4776
2851,2011-06-02,TATAMOTORS,EQ,1079.9,1070.0,1070.0,1042.20,1046.15,1048.20,1050.62,2604237,2.736056e+14,74650.0,1149341.0,0.4413
2852,2011-06-03,TATAMOTORS,EQ,1048.2,1048.0,1058.0,1014.25,1024.60,1023.80,1031.52,3600090,3.713581e+14,94611.0,1472425.0,0.4090
2853,2011-06-06,TATAMOTORS,EQ,1023.8,1011.5,1031.8,1010.25,1022.20,1023.70,1020.38,2076683,2.119014e+14,64914.0,451682.0,0.2175
2854,2011-06-07,TATAMOTORS,EQ,1023.7,1017.0,1033.8,1015.65,1028.00,1027.20,1027.38,2117760,2.175745e+14,56772.0,805423.0,0.3803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5301,2021-04-26,TATAMOTORS,EQ,294.0,297.0,299.0,294.60,295.85,295.40,296.48,30583139,9.067386e+14,173282.0,3291167.0,0.1076
5302,2021-04-27,TATAMOTORS,EQ,295.4,295.7,302.5,295.10,302.10,301.50,299.05,35040532,1.047879e+15,191627.0,5215100.0,0.1488
5303,2021-04-28,TATAMOTORS,EQ,301.5,303.5,309.5,303.00,305.15,305.90,307.22,44668126,1.372278e+15,264159.0,5116568.0,0.1145
5304,2021-04-29,TATAMOTORS,EQ,305.9,308.9,310.0,301.25,302.20,301.90,304.77,36647292,1.116900e+15,186996.0,4193346.0,0.1144
5305,2021-04-30,TATAMOTORS,EQ,301.9,298.2,301.3,292.55,293.10,293.85,297.01,36121668,1.072849e+15,227806.0,7898988.0,0.2187